version: '3.9'

services:

  fe-app:
    build:
      context: angular-ui
    ports:
      - "80:80"

  app:
    build:
      context: .
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: iosu
    ports:
      - "5432:5432"